# Generated by Django 4.2.7 on 2023-11-07 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='validated',
            new_name='verified',
        ),
    ]
