# Generated by Django 4.2.7 on 2023-11-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0003_rename_validated_otp_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="otp",
            field=models.IntegerField(),
        ),
    ]
