# Generated by Django 4.2.7 on 2023-12-30 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_categorymodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryModel',
            new_name='Category',
        ),
    ]
