# Generated by Django 4.2.7 on 2023-12-30 20:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_slide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='products/')),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('offer_price', models.FloatField(default=0)),
                ('delivery_charge', models.FloatField(default=0)),
                ('star_5', models.IntegerField(default=0)),
                ('star_4', models.IntegerField(default=0)),
                ('star_3', models.IntegerField(default=0)),
                ('star_2', models.IntegerField(default=0)),
                ('star_1', models.IntegerField(default=0)),
                ('cod', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_set', to='backend.category')),
            ],
        ),
    ]
