# Generated by Django 4.2.7 on 2024-01-04 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_pageimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PageImage',
            new_name='PageItem',
        ),
    ]
