# Generated by Django 4.2.7 on 2024-01-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_rename_pageimage_pageitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cart',
            field=models.ManyToManyField(blank=True, related_name='cart_set', to='backend.productoption'),
        ),
        migrations.AddField(
            model_name='user',
            name='wishlist',
            field=models.ManyToManyField(blank=True, to='backend.productoption'),
        ),
        migrations.AlterField(
            model_name='pageitem',
            name='image',
            field=models.ImageField(blank=True, upload_to='pages/'),
        ),
        migrations.AlterField(
            model_name='pageitem',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
