# Generated by Django 4.2.7 on 2024-01-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_user_cart_user_wishlist_alter_pageitem_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cart',
            field=models.ManyToManyField(blank=True, related_name='cart', to='backend.productoption'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='wishlist', to='backend.productoption'),
        ),
    ]
